(function initMessageTypeConstants(globalScope) {
  const NewSiteCore = globalScope.NewSiteCore = globalScope.NewSiteCore || {};

  NewSiteCore.CoreMessageTypes = {
    PROFILE_GET: "NEWSITE_PROFILE_GET",
    PROFILE_SAVE: "NEWSITE_PROFILE_SAVE",
    PROFILE_RESET: "NEWSITE_PROFILE_RESET",
    SELECTOR_TEST: "NEWSITE_SELECTOR_TEST",
    SELECTOR_TEST_ALL: "NEWSITE_SELECTOR_TEST_ALL",
    PAGE_STATE_DETECT: "NEWSITE_PAGE_STATE_DETECT",
    RUN_AUTOMATION: "NEWSITE_RUN_AUTOMATION",
    RUNTIME_STATUS_GET: "NEWSITE_RUNTIME_STATUS_GET",
    DIAGNOSTICS_GET: "NEWSITE_DIAGNOSTICS_GET",
    EXPORT_DIAGNOSTICS: "NEWSITE_EXPORT_DIAGNOSTICS"
  };

  NewSiteCore.GatewayMessageTypes = {
    GATEWAY_STATUS_GET: "AUTODIPSIK_GATEWAY_STATUS_GET",
    GATEWAY_CONNECT: "AUTODIPSIK_GATEWAY_CONNECT",
    GATEWAY_DISCONNECT: "AUTODIPSIK_GATEWAY_DISCONNECT",
    GATEWAY_SELECT_FILE: "AUTODIPSIK_GATEWAY_SELECT_FILE",
    GATEWAY_EXECUTE_UPLOAD: "AUTODIPSIK_GATEWAY_EXECUTE_UPLOAD",
    GATEWAY_EXPORT_DIAGNOSTICS: "AUTODIPSIK_GATEWAY_EXPORT_DIAGNOSTICS"
  };

  NewSiteCore.DeepSeekMessageTypes = {
    CONDITIONAL_WORKFLOW_RUN: "AUTODIPSIK_CONDITIONAL_WORKFLOW_RUN",
    DEEPSEEK_ATTACH_FILE: "AUTODIPSIK_ATTACH_FILE_TO_DEEPSEEK",
    DEEPSEEK_TAB_ENSURE: "AUTODIPSIK_DEEPSEEK_TAB_ENSURE",
    DEEPSEEK_CONTENT_SCRIPT_PING: "AUTODIPSIK_DEEPSEEK_CONTENT_SCRIPT_PING"
  };
})(globalThis);
