(function initTelemetryEventConstants(globalScope) {
  const NewSiteCore = globalScope.NewSiteCore = globalScope.NewSiteCore || {};

  NewSiteCore.CoreTelemetryEvents = {
    EXTENSION_BOOTSTRAP_STARTED: "extension.bootstrap.started",
    EXTENSION_BOOTSTRAP_COMPLETED: "extension.bootstrap.completed",
    EXTENSION_MESSAGE_RECEIVED: "extension.message.received",
    EXTENSION_MESSAGE_FORWARDED: "extension.message.forwarded",
    EXTENSION_MESSAGE_FAILED: "extension.message.failed",
    PROFILE_LOADED: "site.profile.loaded",
    PROFILE_SAVED: "site.profile.saved",
    PROFILE_VALIDATION_FAILED: "site.profile.validation_failed",
    SELECTOR_TEST_STARTED: "site.selector.test.started",
    SELECTOR_TEST_COMPLETED: "site.selector.test.completed",
    SELECTOR_TEST_FAILED: "site.selector.test.failed",
    SELECTOR_BROKEN: "site.selector.broken",
    SELECTOR_FALLBACK_USED: "site.selector.fallback_used",
    PAGE_STATE_DETECT_STARTED: "site.page_state.detect.started",
    PAGE_STATE_DETECT_COMPLETED: "site.page_state.detect.completed",
    PAGE_STATE_DETECT_FAILED: "site.page_state.detect.failed",
    WORKFLOW_STARTED: "site.workflow.started",
    WORKFLOW_STEP_STARTED: "site.workflow.step.started",
    WORKFLOW_STEP_COMPLETED: "site.workflow.step.completed",
    WORKFLOW_STEP_FAILED: "site.workflow.step.failed",
    WORKFLOW_COMPLETED: "site.workflow.completed",
    WORKFLOW_FAILED: "site.workflow.failed",
    DIAGNOSTIC_EXPORT_STARTED: "diagnostic.export.started",
    DIAGNOSTIC_EXPORT_COMPLETED: "diagnostic.export.completed",
    DIAGNOSTIC_PACKAGE_CREATED: "diagnostic.package.created",
    DIAGNOSTIC_PACKAGE_EXPORTED: "diagnostic.package.exported"
  };

  NewSiteCore.GatewayTelemetryEvents = {
    GATEWAY_CONNECTING: "extension.gateway.connecting",
    GATEWAY_CONNECTED: "extension.gateway.connected",
    GATEWAY_DISCONNECTED: "extension.gateway.disconnected",
    GATEWAY_RECONNECTING: "extension.gateway.reconnecting",
    GATEWAY_MESSAGE_SENT: "extension.gateway.message.sent",
    GATEWAY_MESSAGE_RECEIVED: "extension.gateway.message.received",
    GATEWAY_REQUEST_FAILED: "extension.gateway.request.failed",
    GATEWAY_FILE_SELECTED: "extension.gateway.file.selected"
  };

  NewSiteCore.DeepSeekTelemetryEvents = {
    DEEPSEEK_EXECUTE_CLICKED: "extension.deepseek.execute.clicked",
    DEEPSEEK_TAB_DETECTED: "extension.deepseek.tab.detected",
    DEEPSEEK_ATTACH_STARTED: "extension.deepseek.attach.started",
    DEEPSEEK_ATTACH_COMPLETED: "extension.deepseek.attach.completed",
    DEEPSEEK_ATTACH_FAILED: "extension.deepseek.attach.failed",
    DEEPSEEK_FILE_INPUT_FOUND: "extension.deepseek.file_input.found",
    DEEPSEEK_FILE_INPUT_NOT_FOUND: "extension.deepseek.file_input.not_found",
    DEEPSEEK_WORKFLOW_STARTED: "extension.deepseek.workflow.started",
    DEEPSEEK_PAGE_READY: "extension.deepseek.page.ready",
    DEEPSEEK_CHAT_INPUT_FOUND: "extension.deepseek.chat_input.found",
    DEEPSEEK_FILE_ATTACH_STARTED: "extension.deepseek.file_attach.started",
    DEEPSEEK_FILE_ATTACHED_CONFIRMED: "extension.deepseek.file_attached.confirmed",
    DEEPSEEK_FILE_ATTACH_CONFIRMATION_SKIPPED: "extension.deepseek.file_attach_confirmation.skipped",
    DEEPSEEK_PROMPT_INSERT_STARTED: "extension.deepseek.prompt_insert.started",
    DEEPSEEK_PROMPT_INSERT_COMPLETED: "extension.deepseek.prompt_insert.completed",
    DEEPSEEK_SEND_BUTTON_SEARCH_STARTED: "extension.deepseek.send_button.search.started",
    DEEPSEEK_SEND_BUTTON_FOUND: "extension.deepseek.send_button.found",
    DEEPSEEK_SEND_BUTTON_NOT_FOUND: "extension.deepseek.send_button.not_found",
    DEEPSEEK_SEND_BUTTON_HEURISTIC_USED: "extension.deepseek.send_button.heuristic_used",
    DEEPSEEK_SEND_CLICKED: "extension.deepseek.send.clicked",
    DEEPSEEK_SEND_FAILED: "extension.deepseek.send.failed",
    DEEPSEEK_WORKFLOW_COMPLETED: "extension.deepseek.workflow.completed",
    DEEPSEEK_WORKFLOW_FAILED: "extension.deepseek.workflow.failed",
    DEEPSEEK_DIAGNOSTIC_PACKAGE_CREATED: "extension.deepseek.diagnostic_package.created",
    AUTOMATION_ONE_CLICK_STARTED: "automation.one_click.started",
    AUTOMATION_ONE_CLICK_PRECONDITION_STARTED: "automation.one_click.precondition.started",
    AUTOMATION_ONE_CLICK_PRECONDITION_COMPLETED: "automation.one_click.precondition.completed",
    AUTOMATION_ONE_CLICK_PRECONDITION_FAILED: "automation.one_click.precondition.failed",
    AUTOMATION_ONE_CLICK_COMPLETED: "automation.one_click.completed",
    AUTOMATION_ONE_CLICK_FAILED: "automation.one_click.failed",
    DEEPSEEK_TAB_ENSURE_STARTED: "deepseek.tab.ensure.started",
    DEEPSEEK_TAB_ENSURE_COMPLETED: "deepseek.tab.ensure.completed",
    DEEPSEEK_TAB_ENSURE_FAILED: "deepseek.tab.ensure.failed",
    DEEPSEEK_CONTENT_SCRIPT_PING_STARTED: "deepseek.content_script.ping.started",
    DEEPSEEK_CONTENT_SCRIPT_PING_COMPLETED: "deepseek.content_script.ping.completed",
    DEEPSEEK_CONTENT_SCRIPT_PING_FAILED: "deepseek.content_script.ping.failed",
    DEEPSEEK_CONTENT_SCRIPT_INJECTION_STARTED: "deepseek.content_script.injection.started",
    DEEPSEEK_CONTENT_SCRIPT_INJECTION_COMPLETED: "deepseek.content_script.injection.completed",
    DEEPSEEK_CONTENT_SCRIPT_INJECTION_FAILED: "deepseek.content_script.injection.failed",
    DEEPSEEK_CONTENT_SCRIPT_RETRY_STARTED: "deepseek.content_script.retry.started",
    DEEPSEEK_CONTENT_SCRIPT_RETRY_COMPLETED: "deepseek.content_script.retry.completed",
    DEEPSEEK_CONTENT_SCRIPT_RETRY_FAILED: "deepseek.content_script.retry.failed",
    DEEPSEEK_PREFLIGHT_STARTED: "deepseek.preflight.started",
    DEEPSEEK_PREFLIGHT_COMPLETED: "deepseek.preflight.completed",
    DEEPSEEK_PREFLIGHT_FAILED: "deepseek.preflight.failed",
    DEEPSEEK_FILE_PAYLOAD_RESOLVED: "deepseek.file_payload.resolved"
  };
})(globalThis);
