(function initConstants(globalScope) {
  const NewSiteCore = globalScope.NewSiteCore = globalScope.NewSiteCore || {};

  NewSiteCore.MESSAGE_TYPES = {
    PROFILE_GET: "NEWSITE_PROFILE_GET",
    PROFILE_SAVE: "NEWSITE_PROFILE_SAVE",
    PROFILE_RESET: "NEWSITE_PROFILE_RESET",
    SELECTOR_TEST: "NEWSITE_SELECTOR_TEST",
    SELECTOR_TEST_ALL: "NEWSITE_SELECTOR_TEST_ALL",
    PAGE_STATE_DETECT: "NEWSITE_PAGE_STATE_DETECT",
    RUN_AUTOMATION: "NEWSITE_RUN_AUTOMATION",
    RUNTIME_STATUS_GET: "NEWSITE_RUNTIME_STATUS_GET",
    DIAGNOSTICS_GET: "NEWSITE_DIAGNOSTICS_GET",
    EXPORT_DIAGNOSTICS: "NEWSITE_EXPORT_DIAGNOSTICS",
    GATEWAY_STATUS_GET: "AUTODIPSIK_GATEWAY_STATUS_GET",
    GATEWAY_CONNECT: "AUTODIPSIK_GATEWAY_CONNECT",
    GATEWAY_DISCONNECT: "AUTODIPSIK_GATEWAY_DISCONNECT",
    GATEWAY_SELECT_FILE: "AUTODIPSIK_GATEWAY_SELECT_FILE",
    GATEWAY_EXECUTE_UPLOAD: "AUTODIPSIK_GATEWAY_EXECUTE_UPLOAD",
    GATEWAY_EXPORT_DIAGNOSTICS: "AUTODIPSIK_GATEWAY_EXPORT_DIAGNOSTICS",
    DEEPSEEK_ATTACH_FILE: "AUTODIPSIK_ATTACH_FILE_TO_DEEPSEEK"
  };

  NewSiteCore.STORAGE_KEYS = {
    SITE_PROFILE: "newsite_site_profile",
    EVENT_BUFFER: "telemetry_buffer",
    LAST_WORKFLOW: "last_workflow",
    SELECTOR_HEALTH: "selector_health",
    PAGE_STATE_HISTORY: "page_state_history",
    ERROR_LOG: "error_log",
    RUNTIME_STATUS: "runtime_status",
    DIAGNOSTIC_SNAPSHOT: "diagnostic_snapshot",
    GATEWAY_STATUS: "gateway_status",
    GATEWAY_EVENTS: "gateway_events",
    GATEWAY_SELECTED_FILE: "gateway_selected_file",
    DEEPSEEK_SITE_PROFILE: "deepseek_site_profile"
  };

  NewSiteCore.TELEMETRY_EVENTS = {
    EXTENSION_BOOTSTRAP_STARTED: "extension.bootstrap.started",
    EXTENSION_BOOTSTRAP_COMPLETED: "extension.bootstrap.completed",
    EXTENSION_MESSAGE_RECEIVED: "extension.message.received",
    EXTENSION_MESSAGE_FORWARDED: "extension.message.forwarded",
    EXTENSION_MESSAGE_FAILED: "extension.message.failed",
    PROFILE_LOADED: "site.profile.loaded",
    PROFILE_SAVED: "site.profile.saved",
    PROFILE_VALIDATION_FAILED: "site.profile.validation_failed",
    SELECTOR_TEST_STARTED: "site.selector.test.started",
    SELECTOR_TEST_COMPLETED: "site.selector.test.completed",
    SELECTOR_TEST_FAILED: "site.selector.test.failed",
    SELECTOR_BROKEN: "site.selector.broken",
    SELECTOR_FALLBACK_USED: "site.selector.fallback_used",
    PAGE_STATE_DETECT_STARTED: "site.page_state.detect.started",
    PAGE_STATE_DETECT_COMPLETED: "site.page_state.detect.completed",
    PAGE_STATE_DETECT_FAILED: "site.page_state.detect.failed",
    WORKFLOW_STARTED: "site.workflow.started",
    WORKFLOW_STEP_STARTED: "site.workflow.step.started",
    WORKFLOW_STEP_COMPLETED: "site.workflow.step.completed",
    WORKFLOW_STEP_FAILED: "site.workflow.step.failed",
    WORKFLOW_COMPLETED: "site.workflow.completed",
    WORKFLOW_FAILED: "site.workflow.failed",
    DIAGNOSTIC_EXPORT_STARTED: "diagnostic.export.started",
    DIAGNOSTIC_EXPORT_COMPLETED: "diagnostic.export.completed",
    GATEWAY_CONNECTING: "extension.gateway.connecting",
    GATEWAY_CONNECTED: "extension.gateway.connected",
    GATEWAY_DISCONNECTED: "extension.gateway.disconnected",
    GATEWAY_RECONNECTING: "extension.gateway.reconnecting",
    GATEWAY_MESSAGE_SENT: "extension.gateway.message.sent",
    GATEWAY_MESSAGE_RECEIVED: "extension.gateway.message.received",
    GATEWAY_REQUEST_FAILED: "extension.gateway.request.failed",
    GATEWAY_FILE_SELECTED: "extension.gateway.file.selected",
    DEEPSEEK_EXECUTE_CLICKED: "extension.deepseek.execute.clicked",
    DEEPSEEK_TAB_DETECTED: "extension.deepseek.tab.detected",
    DEEPSEEK_ATTACH_STARTED: "extension.deepseek.attach.started",
    DEEPSEEK_ATTACH_COMPLETED: "extension.deepseek.attach.completed",
    DEEPSEEK_ATTACH_FAILED: "extension.deepseek.attach.failed",
    DEEPSEEK_FILE_INPUT_FOUND: "extension.deepseek.file_input.found",
    DEEPSEEK_FILE_INPUT_NOT_FOUND: "extension.deepseek.file_input.not_found",
    DEEPSEEK_WORKFLOW_STARTED: "extension.deepseek.workflow.started",
    DEEPSEEK_PAGE_READY: "extension.deepseek.page.ready",
    DEEPSEEK_CHAT_INPUT_FOUND: "extension.deepseek.chat_input.found",
    DEEPSEEK_FILE_ATTACH_STARTED: "extension.deepseek.file_attach.started",
    DEEPSEEK_FILE_ATTACHED_CONFIRMED: "extension.deepseek.file_attached.confirmed",
    DEEPSEEK_FILE_ATTACH_CONFIRMATION_SKIPPED: "extension.deepseek.file_attach_confirmation.skipped",
    DEEPSEEK_PROMPT_INSERT_STARTED: "extension.deepseek.prompt_insert.started",
    DEEPSEEK_PROMPT_INSERT_COMPLETED: "extension.deepseek.prompt_insert.completed",
    DEEPSEEK_SEND_BUTTON_FOUND: "extension.deepseek.send_button.found",
    DEEPSEEK_SEND_BUTTON_HEURISTIC_USED: "extension.deepseek.send_button.heuristic_used",
    DEEPSEEK_SEND_CLICKED: "extension.deepseek.send.clicked",
    DEEPSEEK_WORKFLOW_COMPLETED: "extension.deepseek.workflow.completed",
    DEEPSEEK_WORKFLOW_FAILED: "extension.deepseek.workflow.failed",
    DEEPSEEK_DIAGNOSTIC_PACKAGE_CREATED: "extension.deepseek.diagnostic_package.created"
  };
})(globalThis);
